# Generated by Django 3.0 on 2019-12-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('bgg_url', models.CharField(max_length=200, null=True)),
                ('game_id', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('min_players', models.PositiveIntegerField(default=1)),
                ('max_players', models.PositiveIntegerField(default=4)),
                ('avg_time', models.PositiveIntegerField(default=30)),
                ('min_time', models.PositiveIntegerField(default=30)),
                ('max_time', models.PositiveIntegerField(default=30)),
                ('year', models.PositiveIntegerField(default=1998)),
                ('avg_rating', models.FloatField(default=0)),
                ('geek_rating', models.FloatField(default=0)),
                ('num_votes', models.PositiveIntegerField(default=0)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('mechanic', models.CharField(blank=True, max_length=500, null=True)),
                ('owned', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('designer', models.CharField(blank=True, max_length=500, null=True)),
                ('weight', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='GameShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
