# Generated by Django 3.0 on 2019-12-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameshort',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
