# Generated by Django 3.0 on 2019-12-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gameshort_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameshort',
            name='rank',
        ),
    ]
