# Generated by Django 3.0 on 2019-12-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_gameshort_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
