# Generated by Django 3.0 on 2019-12-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191208_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
