# Generated by Django 3.0 on 2019-12-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191208_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='names',
        ),
    ]
