# Generated by Django 3.0 on 2019-12-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191209_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Game Full', 'verbose_name_plural': 'Games Full'},
        ),
        migrations.AlterModelOptions(
            name='gameshort',
            options={'verbose_name': 'Game Short', 'verbose_name_plural': 'Games Short'},
        ),
        migrations.AlterField(
            model_name='game',
            name='bgg_url',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='designer',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mechanic',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='names',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
