# Generated by Django 3.0 on 2019-12-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191209_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='avg_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='owned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(default=1998),
        ),
    ]
