# Generated by Django 2.2.1 on 2019-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191209_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameshort',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
