# Generated by Django 2.2.1 on 2019-12-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_similargame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similargame',
            old_name='rank',
            new_name='ranks',
        ),
        migrations.AlterField(
            model_name='similargame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='api.Game'),
        ),
    ]
