# Generated by Django 2.2.1 on 2019-12-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191211_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarGameConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_rank', models.IntegerField(default=0)),
                ('similar_games_rank', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': 'Connections',
            },
        ),
    ]
