# Generated by Django 2.2.1 on 2019-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191211_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similargameconnection',
            name='similar_games_rank',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
